#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t mmb-boot"
$L "  __  __   __  __   ____         _____   ____   _____   __  __ ";
$L " |  \/  | |  \/  | |  _ \       |__ __| | ___| | __  | |  \/  |";
$L " | |\/| | | |\/| | | |_| |  __    | |   | |__  | | | | | |\/| |";
$L " | |  | | | |  | | |  _  | |__|   | |   | ___| | |_| | | |  | |";
$L " | |  | | | |  | | | |_| |        | |   | |__  |  _  | | |  | |";
$L " |_|  |_| |_|  |_| |____/         |_|   |____| |_| |_| |_|  |_|";
$L "Welcome to Android `getprop ro.build.version.release` offered to you by MoltenMotherBoard team!";
